### PR TITLE
Use Places to express closure captures

### PR DESCRIPTION
**Pull request by arora-aman**
This change is [Reviewable](https://reviewable.io/reviews/sexxi-goose/rust/24)

### CODE REVIEW

**Comment by arora-aman** [comment]
@null-sleep  The FIXME(azhng) probably should be replaced with something like: https://github.com/sexxi-goose/rust/blob/min_capture/compiler/rustc_typeck/src/check/upvar.rs#L750-L771

Though this should also account for Pattern expressions as we had discussed.

image

**Comment by arora-aman** [comment]
I extracted the example programs we wrote for our 463 specification here: http://csclub.uwaterloo.ca/~a52arora/test_suite/spec/

The ones marked `imp` are the important ones, the numbers are just assocaited with the example number from the spec.

We also what to make sure that the cases mentioned in https://github.com/rust-lang/project-rfc-2229/issues/9#issuecomment-660716274 are also added.

**Comment by arora-aman** [comment]
@null-sleep I missed this change when I ported the change to the new compiler structure.
https://github.com/sexxi-goose/rust/blob/use_places_aman/src/librustc_typeck/check/upvar.rs#L425-L430

**Comment by null-sleep** [comment]
image

**Comment by arora-aman** [comment]
#28

**Pull request closed without merging**
